times = {
    "Aguilas": "Rionegro Aguilas",
    "Arsenal": "Arsenal",
    "Atlético-MG": "Atlético MG",
    "Bahia": "Bahia",
    "Botafogo": "Botafogo FR",
    "Chapecoense":"Chapecoense",
    "Corinthians":"Corinthians",
    "Cruzeiro": "Cruzeiro",
    "Flamengo ": "Flamengo",
    "Fluminense": "Fluminense",
    "Internacional": "Internacional",
    "Millonarios": "Millonarios FC",
    "Mirassol": "Mirassol",
    "Palmeiras": "Palmeiras",
    "Ponte Preta": "Ponte Preta",
    "Real Madrid": "Real Madrid",
    "Red Bull Bragantino": "Bragantino",
    "Remo":"Remo",
    "São Paulo": "São Paulo",
    "Vasco": "Vasco da Gama",
    "Macara": "CSD Macará",
    "Los Angeles Galaxy":"LA Galaxy",
    "Criciúma":"Criciúma",
    "River Plate":"River Plate",
    "Blooming":"Blooming",
    "Cerro Porteno":"Cerro Porteno",
    "Sporting Cristal":"Sporting Cristal",
    "Boca Juniors":"Boca Juniors",
    "Universidad Católica":"Universidade Católica",
    
}